config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :bills
  resources :chapters
  resources :books

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/by_topic' => 'pages#search_by_topic', :as => 'topic_search'
  get '/scrape' => 'bills#scrape', :as => 'scrape_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
    OPTIONS = [ "Emenda", 
    "Indicação/Pedido de Providências", 
    "Moção", 
    "Projeto de Decreto Legislativo",
    "Projeto de Emenda à Lei Orgânica Municipal",
    "Projeto de Lei",
    "Projeto de Lei Complementar",
    "Projeto de Lei Orgânica Municipal",
    "Projeto de Resolução",
    "Projeto de Sugestão",
    "Requerimento",
    "Substitutivo",
    "Veto" ]
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create ]
  before_action :set_user, only: %i[ new create ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.user_id = @user.id
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def scrape
    search_type = attr_breadcrumb(params[:choice]).to_s
    url = 'https://sapl.camaranh.rs.gov.br/materia/pesquisar-materia?tipo=' + search_type
    @response = Scraper.parse(url)
    if @response.empty? && @response[:error].nil?
      flash.now[:alert] = response[:error]
    else
      flash.now[:notice] = "Successfully scraped website"
    end
    rescue StandardError => e
      flash.now[:alert] = "Error: #{e}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def attr_breadcrumb(type)
      case type
      when "Emenda"
        return 24
      when "Indicação/Pedido de Providências"
        return 8
      when "Moção"
        return 7
      when "Projeto de Decreto Legislativo"
        return 6
      when "Projeto de Emenda à Lei Orgânica Municipal"
        return 9
      when "Projeto de Lei"
        return 1
      when "Projeto de Lei Complementar"
        return 5
      when "Projeto de Lei Orgânica Municipal"
        return 18
      when "Projeto de Resolução"
        return 2
      when "Projeto de Sugestão"
        return 20
      when "Requerimento"
        return 3
      when "Substitutivo"
        return 25
      when "Veto" 
        return 21
      end
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:title, :summary, :timestamp, :author, :localization, :status, :expiration_date, :last_process_date, :last_process, :attachment_docs, :link)
    end

    def serialized_params
      params.require(:bill).permit(:bill, :authenticity_token)
    end

    def set_user
      @user = current_user
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :timestamp %>
    <%= form.text_field :timestamp, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :localization %>
    <%= form.text_field :localization, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :expiration_date %>
    <%= form.text_field :expiration_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_process_date %>
    <%= form.text_field :last_process_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_process %>
    <%= form.text_field :last_process, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :attachment_docs %>
    <%= form.number_field :attachment_docs, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if bill.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', bill, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if bill.persisted? %>
      <%= link_to "Cancel", bill, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", bills_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Edit Bill</h1>

<%= render 'form', bill: @bill %>

app/views/bills/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 mb-4 mt-4">
      <h1>Bills</h1>
    </div>

    <div class="col-sm-6 text-right mt-4">
    <%= link_to new_bill_path, class: 'btn btn-primary' do %>
      Add New Bill
    <% end %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
      

              <th>Title</th>
              <th>Summary</th>
              <th>Timestamp</th>
              <th>Author</th>
              <th>Localization</th>
              <th>Status</th>
              <th>Expiration date</th>
              <th>Last process date</th>
              <th>Last process status</th>
              <th>Attachment docs</th>
              <th>Link</th>
              
            <th></th>
          
        </tr>
      </thead>

      <tbody>
        <% @bills.each do |bill| %>
          <%= content_tag :tr, id: dom_id(bill), class: dom_class(bill) do %>
            

                        <td><%= bill.title %></td>
                        <td><%= bill.summary %></td>
                        <td><%= bill.timestamp %></td>
                        <td><%= bill.author %></td>
                        <td><%= bill.localization %></td>
                        <td><%= bill.status %></td>
                        <td><%= bill.expiration_date %></td>
                        <td><%= bill.last_process_date %></td>
                        <td><%= bill.last_process_status %></td>
                        <td><%= bill.attachment_docs %></td>
                        <td><%= bill.link %></td>
            
            
              <td><%= link_to 'Show', bill %></td>
            
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form', bill: @bill %>

app/views/bills/scrape.html.erb
<div class="bg-gray-100 overflow-x-hidden">
    <div class="px-6 py-8">
        <div class="flex justify-between container mx-auto">
            <div class="">
                <div class="flex items-center justify-between">
                    <h1 class="text-xl font-bold text-gray-700 md:text-2xl">Results:</h1>
                    <%= link_to "New Search", root_path, class: "btn btn-md btn-secondary" %>
                </div>
                <% if @response.present? %>
                    <% @response.each do |result| %>
                    <div class="mt-6 mb-2">
                    <!-- Div de resultados -->
                            <div class="max-w-4xl px-10 py-6 bg-white rounded-lg shadow-md">
                                <div class="flex justify-between items-center">
                                <span class="font-light text-gray-600"><%= result.timestamp %></span>
                                    <a href="#" class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500"><%= result.localization %></a>
                                </div>
                                <div class="mt-2"><a href="#" class="text-2xl text-gray-700 font-bold hover:underline"><%= result.title %></a>
                                    <p class="mt-2 text-gray-600"><%= result.summary %></p>
                                    <small>Status: <%= result.status %></small>
                                </div>
                                <div class="flex justify-between items-center mt-4"><a href=<%= result.link %>
                                        class="text-blue-500 hover:underline">Read more</a>
                                    <div>
                                        <a href="#" class="flex items-center"><img
                                                    src="https://www.novohamburgo.rs.gov.br/sites/pmnh/files/paragrafo/2018-04/brasao-NH.jpg"
                                                    alt="avatar" class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block">
                                                <h1 class="text-gray-700 font-bold hover:underline"><%= result.author %></h1>
                                        </a>
                                    </div>
                                    <% if current_user %>
                                        <%= link_to "Save Record", bills_path(bill: result.as_json), method: "POST", class: "btn btn-sm btn-success" %>
                                    <% else %>
                                        <%= link_to "Login to Save", bills_path(bill: result.as_json), method: "POST", class: "btn btn-sm btn-success" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end%>
                <% end %>
                <div class="mt-8">
                    <div class="flex">
                        <a href="#" class="mx-1 px-3 py-2 bg-white text-gray-500 font-medium rounded-md cursor-not-allowed">
                            previous
                        </a>
                    
                        <a href="#" class="mx-1 px-3 py-2 bg-white text-gray-700 font-medium hover:bg-blue-500 hover:text-white rounded-md">
                            1
                        </a>
                    
                        <a href="#" class="mx-1 px-3 py-2 bg-white text-gray-700 font-medium hover:bg-blue-500 hover:text-white rounded-md">
                            2
                        </a>
                    
                        <a href="#" class="mx-1 px-3 py-2 bg-white text-gray-700 font-medium hover:bg-blue-500 hover:text-white rounded-md">
                            3
                        </a>
                    
                        <a href="#" class="mx-1 px-3 py-2 bg-white text-gray-700 font-medium hover:bg-blue-500 hover:text-white rounded-md">
                            Next
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

<!-- Page Header component -->

app/views/bills/show.html.erb
<div class="container">
  <div class="page-header">
    <%= link_to bills_path, class: 'btn btn-default' do %>
      All Bills
    <% end %>
    <%= link_to edit_bill_path(@bill), class: 'btn btn-primary' do %>
      Edit
    <% end %>
    <h1>Show bill</h1>
  </div>

  <dl class="dl-horizontal">
    <dt>Title:</dt>
    <dd><%= @bill.title %></dd>

    <dt>Summary:</dt>
    <dd><%= @bill.summary %></dd>

    <dt>Timestamp:</dt>
    <dd><%= @bill.timestamp %></dd>

    <dt>Author:</dt>
    <dd><%= @bill.author %></dd>

    <dt>Localization:</dt>
    <dd><%= @bill.localization %></dd>

    <dt>Status:</dt>
    <dd><%= @bill.status %></dd>

    <dt>Expiration date:</dt>
    <dd><%= @bill.expiration_date %></dd>

    <dt>Last process date:</dt>
    <dd><%= @bill.last_process_date %></dd>

    <dt>Last process Status:</dt>
    <dd><%= @bill.last_process_status %></dd>

    <dt>Attachment docs:</dt>
    <dd><%= @bill.attachment_docs %></dd>

    <dt>Link:</dt>
    <dd><a href="<%= @bill.link %>"><%= @bill.link %></a></dd>

  </dl>
</div>