config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :bills
  resources :chapters
  resources :books

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/by_topic' => 'pages#search_by_topic', :as => 'topic_search'
  get '/scrape' => 'bills#scrape', :as => 'scrape_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chapter, only: %i[ show edit update destroy ]

  # GET /chapters or /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1 or /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters or /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: "Chapter was successfully created." }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1 or /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: "Chapter was successfully updated." }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1 or /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.require(:chapter).permit(:title, :description, :content, :author, :book_id, :user_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: chapter, local: true) do |form| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :book_id %>
    <%= form.text_field :book_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if chapter.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', chapter, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if chapter.persisted? %>
      <%= link_to "Cancel", chapter, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", chapters_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/chapters/_new.html.erb
<body class="bg-cream text-charcoal min-h-screen font-sans leading-normal overflow-x-hidden lg:overflow-auto">
    <main class="flex-1 md:p-0 lg:pt-8 lg:px-8 md:ml-24 flex flex-col">
    <section class="bg-cream-lighter p-4 shadow">
    <div class="md:flex">
      <h2 class="md:w-1/3 uppercase tracking-wide text-sm sm:text-lg mb-6">Create New Location</h2>
    </div>
    <form>
      <div class="md:flex mb-8">
        <div class="md:w-1/3">
          <legend class="uppercase tracking-wide text-sm">Location</legend>
          <p class="text-xs font-light text-red">This entire section is required.</p>
        </div>
      <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
        <div class="mb-4">
          <label class="block uppercase tracking-wide text-xs font-bold">Name</label>
          <input class="w-full shadow-inner p-4 border-0" type="text" name="name" placeholder="Acme Mfg. Co.">
        </div>
        <div class="md:flex mb-4">
          <div class="md:flex-1 md:pr-3">
            <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Street Address</label>
            <input class="w-full shadow-inner p-4 border-0" type="text" name="address_street" placeholder="555 Roadrunner Lane">
          </div>
          <div class="md:flex-1 md:pl-3">
            <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Building/Suite No.</label>
            <input class="w-full shadow-inner p-4 border-0" type="text" name="address_number" placeholder="#3">
            <span class="text-xs mb-4 font-thin">We lied, this isn't required.</span>
          </div>
        </div>
        <div class="md:flex mb-4">
          <div class="md:flex-1 md:pr-3">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Latitude</label>
              <input class="w-full shadow-inner p-4 border-0" type="text" name="lat" placeholder="30.0455542">
            </div>
            <div class="md:flex-1 md:pl-3">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Longitude</label>
              <input class="w-full shadow-inner p-4 border-0" type="text" name="lon" placeholder="-99.1405168">
            </div>
          </div>
        </div>
      </div>
      <div class="md:flex mb-8">
        <div class="md:w-1/3">
          <legend class="uppercase tracking-wide text-sm">Contact</legend>
        </div>
        <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
          <div class="mb-4">
            <label class="block uppercase tracking-wide text-xs font-bold">Phone</label>
            <input class="w-full shadow-inner p-4 border-0" type="tel" name="phone" placeholder="(555) 555-5555">
          </div>
          <div class="mb-4">
            <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">URL</label>
            <input class="w-full shadow-inner p-4 border-0" type="url" name="url" placeholder="acme.co">
          </div>
          <div class="mb-4">
            <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Email</label>
            <input class="w-full shadow-inner p-4 border-0" type="email" name="email" placeholder="contact@acme.co">
          </div>
        </div>
      </div>
      <div class="md:flex">
        <div class="md:w-1/3">
          <legend class="uppercase tracking-wide text-sm">Social</legend>
        </div>
        <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
          <div class="md:flex mb-4">
            <div class="md:flex-1 md:pr-3">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Facebook</label>
              <div class="w-full flex">
                <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">facebook.com/</span>
                <input class="flex-1 shadow-inner p-4 border-0" type="text" name="facebook" placeholder="acmeco">
              </div>
            </div>
            <div class="md:flex-1 md:pl-3 mt-2 md:mt-0">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Twitter</label>
              <div class="w-full flex">
                <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">twitter.com/</span>
                <input class="flex-1 shadow-inner p-4 border-0" type="text" name="twitter" placeholder="acmeco">
              </div>
            </div>
          </div>
          <div class="md:flex mb-4">
            <div class="md:flex-1 md:pr-3">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Instagram</label>
              <div class="w-full flex">
                <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">instagram.com/</span>
                <input class="flex-1 shadow-inner p-4 border-0" type="text" name="instagram" placeholder="acmeco">
              </div>
            </div>
            <div class="md:flex-1 md:pl-3 mt-2 md:mt-0">
              <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Yelp</label>
                <div class="w-full flex">
                  <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">yelp.com/</span>
                  <input class="flex-1 shadow-inner p-4 border-0" type="text" name="yelp" placeholder="acmeco">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="md:flex mb-6">
          <div class="md:w-1/3">
            <legend class="uppercase tracking-wide text-sm">Description</legend>
          </div>
          <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
            <textarea class="w-full shadow-inner p-4 border-0" placeholder="We build fine acmes." rows="6"></textarea>
          </div>
        </div>
        <div class="md:flex mb-6">
          <div class="md:w-1/3">
            <legend class="uppercase tracking-wide text-sm">Cover Image</legend>
          </div>
          <div class="md:flex-1 px-3 text-center">
            <div class="button bg-gold hover:bg-gold-dark text-cream mx-auto cusor-pointer relative">
              <input class="opacity-0 absolute pin-x pin-y" type="file" name="cover_image">
              Add Cover Image
            </div>
          </div>
        </div>
        <div class="md:flex mb-6 border border-t-1 border-b-0 border-x-0 border-cream-dark">
          <div class="md:flex-1 px-3 text-center md:text-right">
            <input type="hidden" name="sponsor" value="0">
            <input class="button text-cream-lighter bg-brick hover:bg-brick-dark" type="submit" value="Create Location">
          </div>
        </div>
      </form>
    </section>
    </main>
  </body>

app/views/chapters/edit.html.erb
<h1>Edit Chapter</h1>

<%= render 'form', chapter: @chapter %>

app/views/chapters/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Chapters</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_chapter_path, class: 'btn btn-primary' do %>
    Add New Chapter
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Description</th>
            <th>Content</th>
            <th>Author</th>
            <th>Book</th>
            <th>User</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @chapters.each do |chapter| %>
        <%= content_tag :tr, id: dom_id(chapter), class: dom_class(chapter) do %>
          

                      <td><%= chapter.title %></td>
                      <td><%= chapter.description %></td>
                      <td><%= chapter.content %></td>
                      <td><%= chapter.author %></td>
                      <td><%= chapter.book %></td>
                      <td><%= chapter.user %></td>
          
          
            <td><%= link_to 'Show', chapter %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form', chapter: @chapter %>

app/views/chapters/show.html.erb
<div class="page-header">
  <%= link_to chapters_path, class: 'btn btn-default' do %>
    All Chapters
  <% end %>
  <%= link_to edit_chapter_path(@chapter), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show chapter</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @chapter.title %></dd>

  <dt>Description:</dt>
  <dd><%= @chapter.description %></dd>

  <dt>Content:</dt>
  <dd><%= @chapter.content %></dd>

  <dt>Author:</dt>
  <dd><%= @chapter.author %></dd>

  <dt>Book:</dt>
  <dd><%= @chapter.book %></dd>

  <dt>User:</dt>
  <dd><%= @chapter.user %></dd>

</dl>